# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'recipe_gui.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1208, 568)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 280, 1180, 291))
        self.tabWidget.setObjectName("tabWidget")
        self.tabFermentables = QtWidgets.QWidget()
        self.tabFermentables.setObjectName("tabFermentables")
        self.addfermentablesButton = QtWidgets.QPushButton(self.tabFermentables)
        self.addfermentablesButton.setGeometry(QtCore.QRect(0, 0, 113, 32))
        self.addfermentablesButton.setObjectName("addfermentablesButton")
        self.fermentableTable = QtWidgets.QTableWidget(self.tabFermentables)
        self.fermentableTable.setGeometry(QtCore.QRect(0, 30, 1180, 230))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.fermentableTable.setFont(font)
        self.fermentableTable.setAutoScrollMargin(16)
        self.fermentableTable.setAlternatingRowColors(True)
        self.fermentableTable.setColumnCount(9)
        self.fermentableTable.setObjectName("fermentableTable")
        self.fermentableTable.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.fermentableTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.fermentableTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.fermentableTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.fermentableTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.fermentableTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.fermentableTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.fermentableTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.fermentableTable.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.fermentableTable.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.fermentableTable.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(195, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        item.setFlags(QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.fermentableTable.setItem(0, 4, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(195, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        item.setFlags(QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.fermentableTable.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(195, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        item.setFlags(QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.fermentableTable.setItem(0, 6, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(195, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        item.setFlags(QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.fermentableTable.setItem(0, 7, item)
        self.fermentableTable.horizontalHeader().setCascadingSectionResizes(False)
        self.fermentableTable.horizontalHeader().setDefaultSectionSize(100)
        self.fermentableTable.horizontalHeader().setStretchLastSection(False)
        self.fermentableTable.verticalHeader().setVisible(False)
        self.fermentableTable.verticalHeader().setHighlightSections(True)
        self.pushButton = QtWidgets.QPushButton(self.tabFermentables)
        self.pushButton.setGeometry(QtCore.QRect(220, 0, 113, 32))
        self.pushButton.setObjectName("pushButton")
        self.tabWidget.addTab(self.tabFermentables, "")
        self.tabHops = QtWidgets.QWidget()
        self.tabHops.setObjectName("tabHops")
        self.hopsTable = QtWidgets.QTableWidget(self.tabHops)
        self.hopsTable.setGeometry(QtCore.QRect(0, 30, 1180, 230))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.hopsTable.setFont(font)
        self.hopsTable.setAlternatingRowColors(True)
        self.hopsTable.setColumnCount(9)
        self.hopsTable.setObjectName("hopsTable")
        self.hopsTable.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.hopsTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.hopsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.hopsTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.hopsTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.hopsTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.hopsTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.hopsTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.hopsTable.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.hopsTable.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.hopsTable.setHorizontalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(195, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        item.setFlags(QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.hopsTable.setItem(0, 5, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(195, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        item.setFlags(QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.hopsTable.setItem(0, 6, item)
        item = QtWidgets.QTableWidgetItem()
        brush = QtGui.QBrush(QtGui.QColor(195, 200, 200))
        brush.setStyle(QtCore.Qt.SolidPattern)
        item.setBackground(brush)
        item.setFlags(QtCore.Qt.ItemIsEditable|QtCore.Qt.ItemIsDragEnabled|QtCore.Qt.ItemIsUserCheckable|QtCore.Qt.ItemIsEnabled)
        self.hopsTable.setItem(0, 7, item)
        self.hopsTable.horizontalHeader().setDefaultSectionSize(100)
        self.hopsTable.verticalHeader().setVisible(False)
        self.addhopsButton = QtWidgets.QPushButton(self.tabHops)
        self.addhopsButton.setGeometry(QtCore.QRect(0, 0, 113, 32))
        self.addhopsButton.setObjectName("addhopsButton")
        self.tabWidget.addTab(self.tabHops, "")
        self.stat_tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.stat_tableWidget.setGeometry(QtCore.QRect(890, 10, 301, 271))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.stat_tableWidget.setFont(font)
        self.stat_tableWidget.setObjectName("stat_tableWidget")
        self.stat_tableWidget.setColumnCount(2)
        self.stat_tableWidget.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.stat_tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.stat_tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.stat_tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.stat_tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.stat_tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.stat_tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.stat_tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.stat_tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.stat_tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.stat_tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.stat_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.stat_tableWidget.setHorizontalHeaderItem(1, item)
        self.stat_tableWidget.horizontalHeader().setStretchLastSection(True)
        self.stat_tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.stat_tableWidget.verticalHeader().setDefaultSectionSize(25)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 10, 431, 201))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(1)
        self.tableWidget.setRowCount(6)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget_2 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget_2.setGeometry(QtCore.QRect(450, 10, 201, 231))
        self.tableWidget_2.setObjectName("tableWidget_2")
        self.tableWidget_2.setColumnCount(1)
        self.tableWidget_2.setRowCount(7)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        self.tableWidget_2.horizontalHeader().setStretchLastSection(True)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1208, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExport_Recipe = QtWidgets.QAction(MainWindow)
        self.actionExport_Recipe.setObjectName("actionExport_Recipe")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionExport_Recipe)
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Beer Recipe Calculator"))
        self.addfermentablesButton.setText(_translate("MainWindow", "Add Row"))
        item = self.fermentableTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.fermentableTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Type"))
        item = self.fermentableTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Fermentable"))
        item = self.fermentableTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Amount"))
        item = self.fermentableTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "lb or oz"))
        item = self.fermentableTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "%"))
        item = self.fermentableTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "PPG"))
        item = self.fermentableTable.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "GU"))
        item = self.fermentableTable.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "L"))
        item = self.fermentableTable.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Cost"))
        __sortingEnabled = self.fermentableTable.isSortingEnabled()
        self.fermentableTable.setSortingEnabled(False)
        self.fermentableTable.setSortingEnabled(__sortingEnabled)
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabFermentables), _translate("MainWindow", "Fermentables"))
        item = self.hopsTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.hopsTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Type"))
        item = self.hopsTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Hops"))
        item = self.hopsTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Amount (oz)"))
        item = self.hopsTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "AA%"))
        item = self.hopsTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Time"))
        item = self.hopsTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "AAU"))
        item = self.hopsTable.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Utilization (%)"))
        item = self.hopsTable.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "IBU"))
        item = self.hopsTable.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Cost"))
        __sortingEnabled = self.hopsTable.isSortingEnabled()
        self.hopsTable.setSortingEnabled(False)
        self.hopsTable.setSortingEnabled(__sortingEnabled)
        self.addhopsButton.setText(_translate("MainWindow", "Add Row"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabHops), _translate("MainWindow", "Hops"))
        item = self.stat_tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Original Gravity"))
        item = self.stat_tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Boil Gravity"))
        item = self.stat_tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Final Gravity"))
        item = self.stat_tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "ABV Standard"))
        item = self.stat_tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "ABV Complex"))
        item = self.stat_tableWidget.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "SRM Morey"))
        item = self.stat_tableWidget.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "SRM Mosher"))
        item = self.stat_tableWidget.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "SRM Daniels"))
        item = self.stat_tableWidget.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "EBC Morey"))
        item = self.stat_tableWidget.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "IBU Tinseth"))
        item = self.stat_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Recipe"))
        item = self.stat_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "BJCP"))
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Name"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Goal"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Style"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Sub Category"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "Brew Day"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "System"))
        item = self.tableWidget_2.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Batch Volume (gal)"))
        item = self.tableWidget_2.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Boil Volume (gal)"))
        item = self.tableWidget_2.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Final Volume (gal)"))
        item = self.tableWidget_2.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "Boil Time (min)"))
        item = self.tableWidget_2.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "Total Gravity"))
        item = self.tableWidget_2.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "BU/GU"))
        item = self.tableWidget_2.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "Mash Efficiency"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionNew.setText(_translate("MainWindow", "New..."))
        self.actionOpen.setText(_translate("MainWindow", "Import Recipe..."))
        self.actionExport_Recipe.setText(_translate("MainWindow", "Export Recipe..."))
        self.actionExit.setText(_translate("MainWindow", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
