# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'recipe_gui.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1208, 594)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(10, 280, 1180, 291))
        self.tabWidget.setObjectName("tabWidget")
        self.tabFermentables = QtWidgets.QWidget()
        self.tabFermentables.setObjectName("tabFermentables")
        self.addfermentablesButton = QtWidgets.QPushButton(self.tabFermentables)
        self.addfermentablesButton.setGeometry(QtCore.QRect(0, 0, 113, 32))
        self.addfermentablesButton.setObjectName("addfermentablesButton")
        self.fermentableTable = QtWidgets.QTableWidget(self.tabFermentables)
        self.fermentableTable.setGeometry(QtCore.QRect(0, 30, 1180, 230))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.fermentableTable.setFont(font)
        self.fermentableTable.setAutoScrollMargin(16)
        self.fermentableTable.setAlternatingRowColors(True)
        self.fermentableTable.setColumnCount(9)
        self.fermentableTable.setObjectName("fermentableTable")
        self.fermentableTable.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.fermentableTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.fermentableTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.fermentableTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.fermentableTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.fermentableTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.fermentableTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.fermentableTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.fermentableTable.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.fermentableTable.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.fermentableTable.setHorizontalHeaderItem(8, item)
        self.fermentableTable.horizontalHeader().setCascadingSectionResizes(False)
        self.fermentableTable.horizontalHeader().setDefaultSectionSize(100)
        self.fermentableTable.horizontalHeader().setStretchLastSection(False)
        self.fermentableTable.verticalHeader().setVisible(False)
        self.fermentableTable.verticalHeader().setHighlightSections(True)
        self.tabWidget.addTab(self.tabFermentables, "")
        self.tabHops = QtWidgets.QWidget()
        self.tabHops.setObjectName("tabHops")
        self.hopsTable = QtWidgets.QTableWidget(self.tabHops)
        self.hopsTable.setGeometry(QtCore.QRect(0, 30, 1180, 230))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.hopsTable.setFont(font)
        self.hopsTable.setAlternatingRowColors(True)
        self.hopsTable.setColumnCount(9)
        self.hopsTable.setObjectName("hopsTable")
        self.hopsTable.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.hopsTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.hopsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.hopsTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.hopsTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.hopsTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.hopsTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.hopsTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.hopsTable.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.hopsTable.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.hopsTable.setHorizontalHeaderItem(8, item)
        self.hopsTable.horizontalHeader().setDefaultSectionSize(100)
        self.hopsTable.verticalHeader().setVisible(False)
        self.addhopsButton = QtWidgets.QPushButton(self.tabHops)
        self.addhopsButton.setGeometry(QtCore.QRect(0, 0, 113, 32))
        self.addhopsButton.setObjectName("addhopsButton")
        self.tabWidget.addTab(self.tabHops, "")
        self.recipe_name_Label = QtWidgets.QLabel(self.centralwidget)
        self.recipe_name_Label.setGeometry(QtCore.QRect(20, 10, 91, 16))
        self.recipe_name_Label.setObjectName("recipe_name_Label")
        self.bjcp_style_Label = QtWidgets.QLabel(self.centralwidget)
        self.bjcp_style_Label.setGeometry(QtCore.QRect(20, 50, 91, 16))
        self.bjcp_style_Label.setObjectName("bjcp_style_Label")
        self.bjcp_subcat_Label = QtWidgets.QLabel(self.centralwidget)
        self.bjcp_subcat_Label.setGeometry(QtCore.QRect(20, 70, 91, 16))
        self.bjcp_subcat_Label.setObjectName("bjcp_subcat_Label")
        self.brew_day_Label = QtWidgets.QLabel(self.centralwidget)
        self.brew_day_Label.setGeometry(QtCore.QRect(20, 90, 91, 16))
        self.brew_day_Label.setObjectName("brew_day_Label")
        self.brew_system_Label = QtWidgets.QLabel(self.centralwidget)
        self.brew_system_Label.setGeometry(QtCore.QRect(20, 110, 91, 16))
        self.brew_system_Label.setObjectName("brew_system_Label")
        self.goal_Label = QtWidgets.QLabel(self.centralwidget)
        self.goal_Label.setGeometry(QtCore.QRect(20, 30, 91, 16))
        self.goal_Label.setObjectName("goal_Label")
        self.batch_volume_Label = QtWidgets.QLabel(self.centralwidget)
        self.batch_volume_Label.setGeometry(QtCore.QRect(300, 10, 131, 16))
        self.batch_volume_Label.setObjectName("batch_volume_Label")
        self.boil_volume_Label = QtWidgets.QLabel(self.centralwidget)
        self.boil_volume_Label.setGeometry(QtCore.QRect(300, 30, 131, 16))
        self.boil_volume_Label.setObjectName("boil_volume_Label")
        self.final_volume_Label = QtWidgets.QLabel(self.centralwidget)
        self.final_volume_Label.setGeometry(QtCore.QRect(300, 50, 131, 16))
        self.final_volume_Label.setObjectName("final_volume_Label")
        self.boil_time_Label = QtWidgets.QLabel(self.centralwidget)
        self.boil_time_Label.setGeometry(QtCore.QRect(300, 70, 131, 16))
        self.boil_time_Label.setObjectName("boil_time_Label")
        self.total_gravity_Label = QtWidgets.QLabel(self.centralwidget)
        self.total_gravity_Label.setGeometry(QtCore.QRect(300, 90, 131, 16))
        self.total_gravity_Label.setObjectName("total_gravity_Label")
        self.bu_gu_ratio_Label = QtWidgets.QLabel(self.centralwidget)
        self.bu_gu_ratio_Label.setGeometry(QtCore.QRect(300, 110, 131, 16))
        self.bu_gu_ratio_Label.setObjectName("bu_gu_ratio_Label")
        self.mash_efficiency_Label = QtWidgets.QLabel(self.centralwidget)
        self.mash_efficiency_Label.setGeometry(QtCore.QRect(300, 130, 101, 16))
        self.mash_efficiency_Label.setObjectName("mash_efficiency_Label")
        self.stat_tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.stat_tableWidget.setGeometry(QtCore.QRect(890, 10, 301, 271))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.stat_tableWidget.setFont(font)
        self.stat_tableWidget.setObjectName("stat_tableWidget")
        self.stat_tableWidget.setColumnCount(2)
        self.stat_tableWidget.setRowCount(10)
        item = QtWidgets.QTableWidgetItem()
        self.stat_tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.stat_tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.stat_tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.stat_tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.stat_tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.stat_tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.stat_tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.stat_tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.stat_tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.stat_tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.stat_tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.stat_tableWidget.setHorizontalHeaderItem(1, item)
        self.stat_tableWidget.horizontalHeader().setStretchLastSection(True)
        self.stat_tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.stat_tableWidget.verticalHeader().setDefaultSectionSize(25)
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(120, 10, 113, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(120, 30, 113, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(120, 50, 113, 21))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(120, 70, 113, 21))
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(120, 90, 113, 21))
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.lineEdit_6 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_6.setGeometry(QtCore.QRect(120, 110, 113, 21))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_7.setGeometry(QtCore.QRect(430, 10, 113, 21))
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.lineEdit_8 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_8.setGeometry(QtCore.QRect(430, 30, 113, 21))
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_9.setGeometry(QtCore.QRect(430, 50, 113, 21))
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.lineEdit_10 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_10.setGeometry(QtCore.QRect(430, 70, 113, 21))
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.lineEdit_11 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_11.setGeometry(QtCore.QRect(430, 90, 113, 21))
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.lineEdit_12 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_12.setGeometry(QtCore.QRect(430, 110, 113, 21))
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.lineEdit_13 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_13.setGeometry(QtCore.QRect(430, 130, 113, 21))
        self.lineEdit_13.setObjectName("lineEdit_13")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1208, 22))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew = QtWidgets.QAction(MainWindow)
        self.actionNew.setObjectName("actionNew")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExport_Recipe = QtWidgets.QAction(MainWindow)
        self.actionExport_Recipe.setObjectName("actionExport_Recipe")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFile.addAction(self.actionNew)
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionExport_Recipe)
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Beer Recipe Calculator"))
        self.addfermentablesButton.setText(_translate("MainWindow", "Add Row"))
        item = self.fermentableTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.fermentableTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Type"))
        item = self.fermentableTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Fermentable"))
        item = self.fermentableTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Amount"))
        item = self.fermentableTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "lb or oz"))
        item = self.fermentableTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "%"))
        item = self.fermentableTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "PPG"))
        item = self.fermentableTable.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "GU"))
        item = self.fermentableTable.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "L"))
        item = self.fermentableTable.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Cost"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabFermentables), _translate("MainWindow", "Fermentables"))
        item = self.hopsTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.hopsTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Type"))
        item = self.hopsTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Hops"))
        item = self.hopsTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Amount (oz)"))
        item = self.hopsTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "AA%"))
        item = self.hopsTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Time"))
        item = self.hopsTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "AAU"))
        item = self.hopsTable.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Utilization (%)"))
        item = self.hopsTable.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "IBU"))
        item = self.hopsTable.horizontalHeaderItem(8)
        item.setText(_translate("MainWindow", "Cost"))
        self.addhopsButton.setText(_translate("MainWindow", "Add Row"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabHops), _translate("MainWindow", "Hops"))
        self.recipe_name_Label.setText(_translate("MainWindow", "Name:"))
        self.bjcp_style_Label.setText(_translate("MainWindow", "Style:"))
        self.bjcp_subcat_Label.setText(_translate("MainWindow", "Sub Category:"))
        self.brew_day_Label.setText(_translate("MainWindow", "Brew Day:"))
        self.brew_system_Label.setText(_translate("MainWindow", "System:"))
        self.goal_Label.setText(_translate("MainWindow", "Goal:"))
        self.batch_volume_Label.setText(_translate("MainWindow", "Batch Volume (gal):"))
        self.boil_volume_Label.setText(_translate("MainWindow", "Boil Volume (gal):"))
        self.final_volume_Label.setText(_translate("MainWindow", "Final Volume (gal):"))
        self.boil_time_Label.setText(_translate("MainWindow", "Boil Time (min):"))
        self.total_gravity_Label.setText(_translate("MainWindow", "Total Gravity:"))
        self.bu_gu_ratio_Label.setText(_translate("MainWindow", "BU/GU:"))
        self.mash_efficiency_Label.setText(_translate("MainWindow", "Mash Efficiency:"))
        item = self.stat_tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "Original Gravity"))
        item = self.stat_tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "Boil Gravity"))
        item = self.stat_tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "Final Gravity"))
        item = self.stat_tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "ABV Standard"))
        item = self.stat_tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "ABV Complex"))
        item = self.stat_tableWidget.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "SRM Morey"))
        item = self.stat_tableWidget.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "SRM Mosher"))
        item = self.stat_tableWidget.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "SRM Daniels"))
        item = self.stat_tableWidget.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "EBC Morey"))
        item = self.stat_tableWidget.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "IBU Tinseth"))
        item = self.stat_tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Recipe"))
        item = self.stat_tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "BJCP"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionNew.setText(_translate("MainWindow", "New..."))
        self.actionOpen.setText(_translate("MainWindow", "Import Recipe..."))
        self.actionExport_Recipe.setText(_translate("MainWindow", "Export Recipe..."))
        self.actionExit.setText(_translate("MainWindow", "Close"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
