# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'recipe_gui.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(865, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.fermentableTable = QtWidgets.QTableWidget(self.centralwidget)
        self.fermentableTable.setGeometry(QtCore.QRect(20, 80, 821, 151))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.fermentableTable.setFont(font)
        self.fermentableTable.setAutoScrollMargin(16)
        self.fermentableTable.setAlternatingRowColors(True)
        self.fermentableTable.setColumnCount(8)
        self.fermentableTable.setObjectName("fermentableTable")
        self.fermentableTable.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.fermentableTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.fermentableTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.fermentableTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.fermentableTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.fermentableTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.fermentableTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.fermentableTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.fermentableTable.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.fermentableTable.setHorizontalHeaderItem(7, item)
        self.addfermentablesButton = QtWidgets.QPushButton(self.centralwidget)
        self.addfermentablesButton.setGeometry(QtCore.QRect(140, 40, 113, 32))
        self.addfermentablesButton.setObjectName("addfermentablesButton")
        self.fermentableLabel = QtWidgets.QLabel(self.centralwidget)
        self.fermentableLabel.setGeometry(QtCore.QRect(20, 40, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.fermentableLabel.setFont(font)
        self.fermentableLabel.setObjectName("fermentableLabel")
        self.hopsLabel = QtWidgets.QLabel(self.centralwidget)
        self.hopsLabel.setGeometry(QtCore.QRect(20, 240, 60, 31))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.hopsLabel.setFont(font)
        self.hopsLabel.setObjectName("hopsLabel")
        self.hopsTable = QtWidgets.QTableWidget(self.centralwidget)
        self.hopsTable.setGeometry(QtCore.QRect(20, 280, 821, 151))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.hopsTable.setFont(font)
        self.hopsTable.setAlternatingRowColors(True)
        self.hopsTable.setColumnCount(8)
        self.hopsTable.setObjectName("hopsTable")
        self.hopsTable.setRowCount(1)
        item = QtWidgets.QTableWidgetItem()
        self.hopsTable.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.hopsTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.hopsTable.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.hopsTable.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.hopsTable.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.hopsTable.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.hopsTable.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.hopsTable.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.hopsTable.setHorizontalHeaderItem(7, item)
        self.addhopsButton = QtWidgets.QPushButton(self.centralwidget)
        self.addhopsButton.setGeometry(QtCore.QRect(140, 240, 113, 32))
        self.addhopsButton.setObjectName("addhopsButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 865, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Beer Recipe Calculator"))
        item = self.fermentableTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.fermentableTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Fermentable"))
        item = self.fermentableTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Type"))
        item = self.fermentableTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Amount (lbs)"))
        item = self.fermentableTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "% of Grain Bill"))
        item = self.fermentableTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "PPG"))
        item = self.fermentableTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Gravity Unit"))
        item = self.fermentableTable.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Lovibond"))
        item = self.fermentableTable.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Cost"))
        self.addfermentablesButton.setText(_translate("MainWindow", "Add Row"))
        self.fermentableLabel.setText(_translate("MainWindow", "Fermentables"))
        self.hopsLabel.setText(_translate("MainWindow", "Hops"))
        item = self.hopsTable.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.hopsTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Hops"))
        item = self.hopsTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Amount (oz)"))
        item = self.hopsTable.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "AA%"))
        item = self.hopsTable.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Time"))
        item = self.hopsTable.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "AAU"))
        item = self.hopsTable.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Utilization (%)"))
        item = self.hopsTable.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "IBU"))
        item = self.hopsTable.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "Cost"))
        self.addhopsButton.setText(_translate("MainWindow", "Add Row"))
